added router
PeaksoftFrontend/Bilingual-js2 pull request #38
Opened 2024-10-28 16:34 UTC by Samirkosh

2024-10-29 20:51 UTC, ZhakshylykNasip reviewed
![Снимок экрана 2024-10-29 в 23 50 16](https://github.com/user-attachments/assets/2e9094b8-0079-4f7c-a115-5d84f0cdab5a)

role GUEST болгондо to begin деген конпканы басканда login page чыксын

logo басканда основной страницага жонотуп койсун

2024-10-29 20:56 UTC, ZhakshylykNasip commented on src/routes/routes.jsx
> +export const AppRoutes = () => {
AppRoutes вызови в App.jsx

2024-10-31 16:37 UTC, ZhakshylykNasip approved these changes

2024-10-31 17:04 UTC, AziatAbd requested changes

2024-10-31 17:04 UTC, AziatAbd commented on src/routes/routes.jsx
> +    },
При входе сделайте Navigate сразу на test а то в начале пустая страница

2024-10-31 17:04 UTC, AziatAbd commented on src/routes/routes.jsx
> +    },
здесь тоже самое только на createTest

2024-10-31 18:58 UTC, merged